FROM phusion/baseimage:0.9.17
MAINTAINER Excellent Person <fill@me.in>

CMD ["/sbin/my_init"]

RUN sudo apt-get install software-properties-common
RUN add-apt-repository -y ppa:webupd8team/java \
&& apt-get update \
&& echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections \
&& apt-get install -y \
software-properties-common \
oracle-java8-installer

RUN mkdir /srv/witan.workspace-peer

ADD . /srv/witan.workspace-peer

RUN mkdir -p /etc/my_init.d
ADD script/run_integration.sh /etc/my_init.d/run_integration_tests.sh

EXPOSE 40200/tcp
EXPOSE 40200/udp

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /var/tmp/*
